#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LOVEMATCH")]
public partial class LoveMatchDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertUsuario(Usuario instance);
  partial void UpdateUsuario(Usuario instance);
  partial void DeleteUsuario(Usuario instance);
  #endregion
	
	public LoveMatchDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["LOVEMATCHConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public LoveMatchDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public LoveMatchDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public LoveMatchDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public LoveMatchDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Usuario> Usuarios
	{
		get
		{
			return this.GetTable<Usuario>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuarios")]
public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _usuario1;
	
	private string _contraseña;
	
	private string _correo;
	
	private string _pais;
	
	private System.Nullable<System.DateTime> _fecha_nacimiento;
	
	private string _sexo;
	
	private string _interes;
	
	private string _busca;
	
	private int _id_usuario;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onusuario1Changing(string value);
    partial void Onusuario1Changed();
    partial void OncontraseñaChanging(string value);
    partial void OncontraseñaChanged();
    partial void OncorreoChanging(string value);
    partial void OncorreoChanged();
    partial void OnpaisChanging(string value);
    partial void OnpaisChanged();
    partial void Onfecha_nacimientoChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_nacimientoChanged();
    partial void OnsexoChanging(string value);
    partial void OnsexoChanged();
    partial void OninteresChanging(string value);
    partial void OninteresChanged();
    partial void OnbuscaChanging(string value);
    partial void OnbuscaChanged();
    partial void Onid_usuarioChanging(int value);
    partial void Onid_usuarioChanged();
    #endregion
	
	public Usuario()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="usuario", Storage="_usuario1", DbType="VarChar(50)")]
	public string usuario1
	{
		get
		{
			return this._usuario1;
		}
		set
		{
			if ((this._usuario1 != value))
			{
				this.Onusuario1Changing(value);
				this.SendPropertyChanging();
				this._usuario1 = value;
				this.SendPropertyChanged("usuario1");
				this.Onusuario1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contraseña", DbType="VarChar(50)")]
	public string contraseña
	{
		get
		{
			return this._contraseña;
		}
		set
		{
			if ((this._contraseña != value))
			{
				this.OncontraseñaChanging(value);
				this.SendPropertyChanging();
				this._contraseña = value;
				this.SendPropertyChanged("contraseña");
				this.OncontraseñaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(30)")]
	public string correo
	{
		get
		{
			return this._correo;
		}
		set
		{
			if ((this._correo != value))
			{
				this.OncorreoChanging(value);
				this.SendPropertyChanging();
				this._correo = value;
				this.SendPropertyChanged("correo");
				this.OncorreoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pais", DbType="VarChar(50)")]
	public string pais
	{
		get
		{
			return this._pais;
		}
		set
		{
			if ((this._pais != value))
			{
				this.OnpaisChanging(value);
				this.SendPropertyChanging();
				this._pais = value;
				this.SendPropertyChanged("pais");
				this.OnpaisChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_nacimiento", DbType="Date")]
	public System.Nullable<System.DateTime> fecha_nacimiento
	{
		get
		{
			return this._fecha_nacimiento;
		}
		set
		{
			if ((this._fecha_nacimiento != value))
			{
				this.Onfecha_nacimientoChanging(value);
				this.SendPropertyChanging();
				this._fecha_nacimiento = value;
				this.SendPropertyChanged("fecha_nacimiento");
				this.Onfecha_nacimientoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sexo", DbType="VarChar(10)")]
	public string sexo
	{
		get
		{
			return this._sexo;
		}
		set
		{
			if ((this._sexo != value))
			{
				this.OnsexoChanging(value);
				this.SendPropertyChanging();
				this._sexo = value;
				this.SendPropertyChanged("sexo");
				this.OnsexoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_interes", DbType="VarChar(20)")]
	public string interes
	{
		get
		{
			return this._interes;
		}
		set
		{
			if ((this._interes != value))
			{
				this.OninteresChanging(value);
				this.SendPropertyChanging();
				this._interes = value;
				this.SendPropertyChanged("interes");
				this.OninteresChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_busca", DbType="NVarChar(20)")]
	public string busca
	{
		get
		{
			return this._busca;
		}
		set
		{
			if ((this._busca != value))
			{
				this.OnbuscaChanging(value);
				this.SendPropertyChanging();
				this._busca = value;
				this.SendPropertyChanged("busca");
				this.OnbuscaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id_usuario
	{
		get
		{
			return this._id_usuario;
		}
		set
		{
			if ((this._id_usuario != value))
			{
				this.Onid_usuarioChanging(value);
				this.SendPropertyChanging();
				this._id_usuario = value;
				this.SendPropertyChanged("id_usuario");
				this.Onid_usuarioChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
